export const plantList = [
	{
		name: 'monstera',
		category: 'classique',
		id: '1ed',
        price: 8,
		isBestSale: true,
		isSpecialOffer : true,
		water : 1,
		light : 2,
	},
	{
		name: 'ficus lyrata',
		category: 'classique',
		id: '2ab',
        price: 23,
		water : 2,
		light : 2,
	},
	{
		name: 'pothos argenté',
		category: 'classique',
		id: '3sd',
        price: 56,
		water : 3,
		light : 1,
		isSpecialOffer : true,
	},
	{
		name: 'yucca',
		category: 'classique',
		id: '4kk',
        price: 5,
		water : 2,
		light : 3,
	},
	{
		name: 'olivier',
		category: 'extérieur',
		id: '5pl',
        price: 80,
		water : 1,
		light : 2,
		isSpecialOffer : true,
	},
	{
		name: 'géranium',
		category: 'extérieur',
		id: '6uo',
        price: 11,
		water : 2,
		light : 3,
	},
	{
		name: 'basilique',
		category: 'extérieur',
		id: '7ie',
        price: 8,
		water : 3,
		light : 1,
	},
	{
		name: 'aloe',
		category: 'plante grasse',
		id: '8fp',
        price: 5,
		water : 3,
		light : 3,
		isBestSale: true,
	},
	{
		name: 'succulente',
		category: 'plante grasse',
		id: '9vn',
        price: 12,
		water : 1,
		light : 1,
		isBestSale: true,
		isSpecialOffer : true,
	}
]