export const plantList = [
	{
		name: 'monstera',
		category: 'classique',
		id: '1ed',
        price: 8,
		isBestSale: true,
		isSpecialOffer : true,
		water : '💧',
		light : '☀️☀️',
	},
	{
		name: 'ficus lyrata',
		category: 'classique',
		id: '2ab',
        price: 23,
		water : '💧💧',
		light : '☀️☀️',
	},
	{
		name: 'pothos argenté',
		category: 'classique',
		id: '3sd',
        price: 56,
		water : '💧💧💧',
		light : '☀️',
		isSpecialOffer : true,
	},
	{
		name: 'yucca',
		category: 'classique',
		id: '4kk',
        price: 5,
		water : '💧💧',
		light : '☀️☀️☀️',
	},
	{
		name: 'olivier',
		category: 'extérieur',
		id: '5pl',
        price: 80,
		water : '💧',
		light : '☀️☀️',
		isSpecialOffer : true,
	},
	{
		name: 'géranium',
		category: 'extérieur',
		id: '6uo',
        price: 11,
		water : '💧💧',
		light : '☀️☀️☀️',
	},
	{
		name: 'basilique',
		category: 'extérieur',
		id: '7ie',
        price: 8,
		water : '💧💧💧',
		light : '☀️',
	},
	{
		name: 'aloe',
		category: 'plante grasse',
		id: '8fp',
        price: 5,
		water : '💧💧💧',
		light : '☀️☀️☀️',
		isBestSale: true,
	},
	{
		name: 'succulente',
		category: 'plante grasse',
		id: '9vn',
        price: 12,
		water : '💧',
		light : '☀️',
		isBestSale: true,
		isSpecialOffer : true,
	}
]